name: lint-format
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install --immutable --immutable-cache
      - name: Lint
        run: yarn lint
